### ISSUE TITLE
Add app logo

### ISSUE THREAD

**Issue by MrKarmakar** [MrKarmakar/cprogrammingclub#11]
add application logo.

**Comment by Sakshy18** [comment]
assign this to me i can design a logo

**Comment by ShubhadeepKarmakar** [comment]
I am working on that.

**Comment by ShubhadeepKarmakar** [comment]
> assign this to me i can design a logo

Hey @Sakshy18 can we be friends, I am new to open source. Finding someone, with whom to discuss things.

**Comment by Sakshy18** [comment]
what kind of logo do u want?..any specific texts ?

**Comment by Sakshy18** [comment]
u can add me on discord sakshi#0100

**Comment by MrKarmakar** [comment]
> ?



> what kind of logo do u want?..any specific texts ?

App name you can use as a text
